### ISSUE TITLE
Landsatscene no longer works on new build

### ISSUE THREAD

**Issue by ForTozs** [chryss/pygaarst#20]
I am having trouble on a new build of pygaarst. An older build on another computer is still functioning properly. The Landsatscene class does not seem to be working. When I try:

`sc = raster.Landsatscene(base_dir + ls_folder + ls_file_folder)`

I get:

`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "pygaarst/landsat.py", line 31, in __init__`
`  File "pygaarst/usgsl1.py", line 59, in __init__`
`  File "pygaarst/mtlutils.py", line 377, in parsemeta`
`  File "pygaarst/mtlutils.py", line 404, in _parsemetastream`
`NameError: global name 'metadatafn' is not defined`

Has anyone seen this before and know what my problem may be? I might should mention I don't have the HDF libraries installed at the moment, but I can't see why that would be an issue. NumPy, GDAL, and PyProj are installed. Thanks.

**Comment by chryss** [comment]
Thanks for your report - I've seen this before, but thought it wasn't present in the current build. I'm doing some testing now and will update.

**Comment by ForTozs** [comment]
Thanks! That would be great.

Jason

**Comment by chryss** [comment]
Hope you got a notification - it should be good now.

**Comment by ForTozs** [comment]
Works like a charm. Thanks!
